name: Apply Repository Settings

on:
  push:
    branches:
      - main  # デフォルトブランチ名を指定

permissions:
  contents: write

jobs:
  set_branch_protection:
    runs-on: ubuntu-latest
    steps:
      - name: Set Branch Protection Rules
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh api \
            --method PUT \
            -H "Accept: application/vnd.github+json" \
            /repos/${{ github.repository }}/branches/main/protection \
            -f required_status_checks.contexts='["ci/test", "ci/lint"]' \
            -f enforce_admins=true \
            -f required_pull_request_reviews.dismiss_stale_reviews=true \
            -f required_pull_request_reviews.require_code_owner_reviews=true \
            -f required_pull_request_reviews.required_approving_review_count=1 \
            -F restrictions=
