name: apisify-deploy

on:
  push:
  schedule:
    # min hours day(month) month day(week)
    - cron: '0 */6 * * *'

jobs:
  devflow:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@master

    - name: context
      uses: okteto/context@latest
      with:
        token: ${{ secrets.OKTETO_TOKEN }}

    - name: "Activate Namespace"
      uses: okteto/namespace@latest

    - name: "Deploy"
      uses: okteto/deploy-stack@latest
      with:
        build: "true"
