name: apisify-authenticate

on:
  schedule:
    # min hours day(month) month day(week)
    - cron: '0 */1 * * *'

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
    - name: Auth
      uses: fjogeleit/http-request-action@master
      with:
        url: https://apisifytrade-${{ github.actor }}.cloud.okteto.net/v1/authenticate
        method: 'GET'
        timeout: 10000
